# Generated by Django 5.0.3 on 2024-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_userprofile_is_employer_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
