# Generated by Django 5.0.3 on 2024-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='employer',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='other_information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_information',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
